/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import doacao.Doacao;
import doacao.DoacaoDAO;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import usuario.Usuario;

/**
 *
 * @author Danylo
 */
public class TelaDoacao extends javax.swing.JFrame {

    Doacao doacao;
    DoacaoDAO dao;
    
  

    public TelaDoacao() {
        initComponents();
        doacao = new Doacao();
        dao = new DoacaoDAO();
    }

    public void limparCampos() {
        doacao = new Doacao();
        tfNomeDoacao.setText("");
        tfNomeDoador.setText("");
        tfDescricaoDoacao.setText("");
    }

    public void preencherDoacao() {
        tfNomeDoacao.setText(doacao.getNomeDoacao());
        tfNomeDoador.setText(doacao.getNomeDoador());
        tfDescricaoDoacao.setText(doacao.getDescricaoProduto());        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomeDoacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfNomeDoador = new javax.swing.JTextField();
        tfDescricaoDoacao = new java.awt.TextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNomeDoacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomeDoacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeDoacaoActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomeDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 360, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Doador:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Receber Doação");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 54));

        tfNomeDoador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeDoadorActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomeDoador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 360, -1));
        getContentPane().add(tfDescricaoDoacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 360, 113));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Descrição:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeDoacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeDoacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeDoacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!tfNomeDoacao.getText().isEmpty() && !tfNomeDoador.getText().isEmpty()
                && !tfDescricaoDoacao.getText().isEmpty()) {            
            doacao.setNomeDoacao(tfNomeDoacao.getText());
            doacao.setNomeDoador(tfNomeDoador.getText());
            doacao.setDescricaoProduto(tfDescricaoDoacao.getText());           
            doacao.setDataEntrada(new Date());            
            doacao.setStatusDoacao("Não");
            doacao.setUsuario(Usuario.getInstance());
            dao.salvar(doacao);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Prencha todos os campos!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfNomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeDoadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDoacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private java.awt.TextArea tfDescricaoDoacao;
    private javax.swing.JTextField tfNomeDoacao;
    private javax.swing.JTextField tfNomeDoador;
    // End of variables declaration//GEN-END:variables
}
