/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import estabelecimento.Estabelecimento;
import estabelecimento.EstabelecimentoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Danylo
 */
public class TelaEstabelecimento extends javax.swing.JFrame {

    Estabelecimento estabelecimento;
    EstabelecimentoDAO estabelecimentoDAO;

    public TelaEstabelecimento() {
        initComponents();

        estabelecimento = new Estabelecimento();
        estabelecimentoDAO = new EstabelecimentoDAO();
    }

    public void limparCampos() {
        estabelecimento = new Estabelecimento();
        tfNomeEstabelecimento.setText("");
        tfRuaEstabelecimento.setText("");
        tfNumeroEstabelecimento.setText("");
        tfBairroEstabelecimento.setText("");
        tfCidadeEstabelecimento.setText("");
    }

    public void preencherEstabelecimento() {
        tfNomeEstabelecimento.setText(estabelecimento.getNomeEstabelecimento());
        tfRuaEstabelecimento.setText(estabelecimento.getRuaEstabelecimento());
        tfNumeroEstabelecimento.setText(estabelecimento.getNomeEstabelecimento());
        tfBairroEstabelecimento.setText(estabelecimento.getBairroEstabelecimento());
        tfCidadeEstabelecimento.setText(estabelecimento.getCidadeEstabelecimento());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomeEstabelecimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfRuaEstabelecimento = new javax.swing.JTextField();
        tfNumeroEstabelecimento = new javax.swing.JTextField();
        tfBairroEstabelecimento = new javax.swing.JTextField();
        tfCidadeEstabelecimento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNomeEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNomeEstabelecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfNomeEstabelecimento.setMinimumSize(null);
        tfNomeEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeEstabelecimentoActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomeEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 256, -1));
        tfNomeEstabelecimento.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");
        jLabel3.setAlignmentX(50.0F);
        jLabel3.setAlignmentY(100.0F);
        jLabel3.setAutoscrolls(true);
        jLabel3.setPreferredSize(null);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));
        jLabel3.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Rua:");
        jLabel4.setAlignmentX(50.0F);
        jLabel4.setAlignmentY(100.0F);
        jLabel4.setAutoscrolls(true);
        jLabel4.setPreferredSize(null);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bairro:");
        jLabel5.setAlignmentX(50.0F);
        jLabel5.setAlignmentY(100.0F);
        jLabel5.setAutoscrolls(true);
        jLabel5.setPreferredSize(null);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        jLabel5.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Número:");
        jLabel6.setAlignmentX(50.0F);
        jLabel6.setAlignmentY(100.0F);
        jLabel6.setAutoscrolls(true);
        jLabel6.setPreferredSize(null);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));
        jLabel6.getAccessibleContext().setAccessibleDescription("");

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jButton4.setText("Salvar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Cadastro Estabelecimento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 130));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cidade:");
        jLabel8.setAlignmentX(50.0F);
        jLabel8.setAlignmentY(100.0F);
        jLabel8.setAutoscrolls(true);
        jLabel8.setPreferredSize(null);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));
        jLabel8.getAccessibleContext().setAccessibleDescription("");

        tfRuaEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfRuaEstabelecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfRuaEstabelecimento.setMinimumSize(null);
        tfRuaEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRuaEstabelecimentoActionPerformed(evt);
            }
        });
        getContentPane().add(tfRuaEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 256, -1));
        tfRuaEstabelecimento.getAccessibleContext().setAccessibleName("");

        tfNumeroEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNumeroEstabelecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfNumeroEstabelecimento.setMinimumSize(null);
        tfNumeroEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroEstabelecimentoActionPerformed(evt);
            }
        });
        getContentPane().add(tfNumeroEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 256, -1));
        tfNumeroEstabelecimento.getAccessibleContext().setAccessibleName("");

        tfBairroEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfBairroEstabelecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfBairroEstabelecimento.setMinimumSize(null);
        tfBairroEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBairroEstabelecimentoActionPerformed(evt);
            }
        });
        getContentPane().add(tfBairroEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 256, -1));
        tfBairroEstabelecimento.getAccessibleContext().setAccessibleName("");

        tfCidadeEstabelecimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCidadeEstabelecimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfCidadeEstabelecimento.setMinimumSize(null);
        tfCidadeEstabelecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCidadeEstabelecimentoActionPerformed(evt);
            }
        });
        getContentPane().add(tfCidadeEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 256, -1));
        tfCidadeEstabelecimento.getAccessibleContext().setAccessibleName("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentX(50.0F);
        jLabel1.setAlignmentY(100.0F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeEstabelecimentoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!tfNomeEstabelecimento.getText().isEmpty() && !tfRuaEstabelecimento.getText().isEmpty()
                && !tfNumeroEstabelecimento.getText().isEmpty() && !tfCidadeEstabelecimento.getText().isEmpty()) {

            estabelecimento.setNomeEstabelecimento(tfNomeEstabelecimento.getText());
            estabelecimento.setRuaEstabelecimento(tfRuaEstabelecimento.getText());
            estabelecimento.setNumeroEstabelecimento(tfNumeroEstabelecimento.getText());
            estabelecimento.setBairroEstabelecimento(tfBairroEstabelecimento.getText());
            estabelecimento.setCidadeEstabelecimento(tfCidadeEstabelecimento.getText());
            estabelecimentoDAO.salvar(estabelecimento);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Prencha todos os campos!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TelaPesquisaEstabelecimento tela = new TelaPesquisaEstabelecimento();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tfRuaEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRuaEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRuaEstabelecimentoActionPerformed

    private void tfNumeroEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroEstabelecimentoActionPerformed

    private void tfBairroEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBairroEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBairroEstabelecimentoActionPerformed

    private void tfCidadeEstabelecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCidadeEstabelecimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCidadeEstabelecimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstabelecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstabelecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstabelecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstabelecimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstabelecimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tfBairroEstabelecimento;
    private javax.swing.JTextField tfCidadeEstabelecimento;
    private javax.swing.JTextField tfNomeEstabelecimento;
    private javax.swing.JTextField tfNumeroEstabelecimento;
    private javax.swing.JTextField tfRuaEstabelecimento;
    // End of variables declaration//GEN-END:variables

}
